name = "isfree-se-dev"
type = "webpack"
workers_dev = true
webpack_config = "node_modules/flareact/webpack"

[env.production]
name = "isfree-se"
workers_dev = false
route = "isfree.se/*"

[site]
bucket = "out"
entry-point = "./"
