name = "isfree-se"
type = "webpack"
account_id = ""
workers_dev = false
route = "edge.isfree.se/*"
zone_id = ""
webpack_config = "node_modules/flareact/webpack"

[site]
bucket = "out"
entry-point = "./"
