name = "isfree-se"
main = "src/worker.tsx"
compatibility_date = "2025-01-24"
assets = { directory = "public" }


[env.production]
route = "isfree.se/*"
workers_dev = false

[env.staging]
workers_dev = true

[observability]
enabled = true
head_sampling_rate = 1

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
