interface NyordYear {
  year: string;
  link: string;
  words: string[];
}

const nyord2025: NyordYear = {
  year: "2025",
  link: "https://www.isof.se/svenska-spraket/nyord/nyordslistan-2025",
  words: [
    "ai-agent",
    "balkongkraftverk",
    "beredskapsodling",
    "broligark",
    "dei",
    "digital-suveränitet",
    "drönarmur",
    "dunkelflaute",
    "existentiell-hållbarhet",
    "finfluerare",
    "handelsbazooka",
    "hjärnröta",
    "hämndtull",
    "klonförening",
    "kulturljudzon",
    "mammakorv",
    "matskatteväxling",
    "pethtest",
    "quadrobics",
    "ragebait",
    "robusthöjande",
    "sixseven",
    "skibidi",
    "solsambruk",
    "trumpviskare",
    "vibbkodning",
    "wokehöger",
  ],
};

const nyord2024: NyordYear = {
  year: "2024",
  link: "https://www.isof.se/svenska-spraket/nyord/nyordslistor/nyordslistan-2024",
  words: [
    "aktivklubb",
    "ankkurva",
    "avokadoskanner",
    "barntorped",
    "bratsommar",
    "coolcation",
    "demure",
    "drakdrönare",
    "dubbelklubb",
    "dubbelsänkning",
    "gisslandiplomati",
    "grisch",
    "grön-gumma",
    "looksmaxing",
    "magdamoderat",
    "mittokrati",
    "quishing",
    "rawdogga",
    "romantasy",
    "skräpballong",
    "skuggflotta",
    "slop",
    "softgirl",
    "swiftiepappa",
    "terian",
    "tiktokifiera",
    "tjejnyår",
    "totalsträckskryptering",
    "tryckarlägenhet",
    "ultrasnabbt-mode",
    "umarell",
    "vänskapsbänk",
  ],
};

const nyord2023: NyordYear = {
  year: "2023",
  link: "https://www.isof.se/svenska-spraket/nyord/nyordslistor/nyordslistan-2023",
  words: [
    "ai-klonad",
    "barbenheimer",
    "bubbelhoppa",
    "cyberresiliens",
    "deinfluencing",
    "det-svenska-tillståndet",
    "dna-pass",
    "dopaminfasta",
    "dubbelswisha",
    "evighetskemikalie",
    "exposekonto",
    "gargasnipe",
    "generativ-ai",
    "grön-kolonialism",
    "hyschpengar",
    "ick",
    "insynsprincip",
    "klivare",
    "korankris",
    "krigssponsor",
    "känslighetsläsare",
    "longtermism",
    "menstrosa",
    "multilojal",
    "nepo-baby",
    "neurodiversitet",
    "prompta",
    "relationism",
    "situationship",
    "snikflation",
    "streamingfarm",
    "tantparkour",
    "toxisk-positivitet",
    "vild-graviditet",
  ],
};

const nyord2022: NyordYear = {
  year: "2022",
  link: "https://www.isof.se/svenska-spraket/nyord/nyordslistor/nyordslistan-2022",
  words: [
    "accelerationism",
    "agrivoltaisk",
    "autokratisering",
    "avkarbonisering",
    "barbiecore",
    "brösta",
    "dödsdoula",
    "edgelord",
    "energifattigdom",
    "energikrig",
    "epadunk",
    "falsk-majoritet",
    "framefotboll",
    "ha-dagen",
    "hungersten",
    "kamikazedrönare",
    "klickkemi",
    "klimatbiljett",
    "klimatskadestånd",
    "matfattigdom",
    "munkmodell",
    "njutningsäktenskap",
    "permakris",
    "putinpris",
    "returmissbrukare",
    "selfiemuseum",
    "smr",
    "smygflation",
    "sporttvätt",
    "spökflyg",
    "urbexare",
    "valförnekare",
    "vertiport",
    "virtuellt-stängsel",
    "väntesorg",
  ],
};

const nyord2021: NyordYear = {
  year: "2021",
  link: "https://www.isof.se/svenska-spraket/nyord/nyordslistor/nyordslistan-2021",
  words: [
    "anosmi",
    "coronabubbla",
    "coronahund",
    "delningsboende",
    "djuränkling",
    "domedagsskrollande",
    "eftervåld",
    "fono",
    "gangfluencer",
    "gaslighta",
    "generation-corona",
    "genombrottsinfektion",
    "giggare",
    "hybridarbete",
    "hybridmöte",
    "jobbonär",
    "jukeboxbio",
    "koldioxidsug",
    "kryptokonst",
    "ljushare",
    "maskne",
    "metaversum",
    "mikrovana",
    "mobilitetshubb",
    "nettonollmål",
    "piratbibliotek",
    "postcovid",
    "snällvägg",
    "spökkök",
    "svinna",
    "svinnlåda",
    "tippningspunkt",
    "vaccinnationalism",
    "vaccinpass",
    "zoomtrötthet",
    "återförvildande",
  ],
};

const allMostRecentFirst = [
  nyord2025,
  nyord2024,
  nyord2023,
  nyord2022,
  nyord2021,
];

export {
  nyord2021,
  nyord2022,
  nyord2023,
  nyord2024,
  nyord2025,
  allMostRecentFirst,
};
