const nyord2024 = [
  "aktivklubb",
  "ankkurva",
  "avokadoskanner",
  "barntorped",
  "bratsommar",
  "coolcation",
  "demure",
  "drakdrönare",
  "dubbelklubb",
  "dubbelsänkning",
  "gisslandiplomati",
  "grisch",
  "grön-gumma",
  "looksmaxing",
  "magdamoderat",
  "mittokrati",
  "quishing",
  "rawdogga",
  "romantasy",
  "skräpballong",
  "skuggflotta",
  "slop",
  "softgirl",
  "swiftiepappa",
  "terian",
  "tiktokifiera",
  "tjejnyår",
  "totalsträckskryptering",
  "tryckarlägenhet",
  "ultrasnabbt-mode",
  "umarell",
  "vänskapsbänk",
];

export { nyord2024 };
