name: Code style 🎩

on:
  - push

jobs:
  codestyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.17.1'
          cache: 'yarn'
      - name: Install packages 📦
        run: yarn install --frozen-lockfile
      - name: Prettier (code formatting)
        run: yarn run prettier
      - name: ESLint (JavaScript linting)
        run: yarn run lint
