name: Code style 🎩

on:
  - push

jobs:
  codestyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "latest"
      - name: Install packages
        run: npm ci
      - name: Prettier
        run: npm run prettier
      - name: ESLint
        run: npm run lint
      - name: TypeCheck
        run: npm run typecheck
